# Generated by Django 5.2.3 on 2025-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('belonging', models.CharField(max_length=100, verbose_name='所属')),
                ('hobby', models.CharField(max_length=200, verbose_name='趣味（カンマ区切りで複数入力可）')),
            ],
        ),
    ]
